"use client";

import Link from 'next/link';

export default function FaithPartnershipBlogPost() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-16 lg:px-8">
      <div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm">
        <p className="text-sm font-semibold uppercase tracking-[0.25em] text-olive">Blog</p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight text-navy">Building Stronger Communities Through Faith-Based Partnerships</h1>
        <p className="mt-4 text-sm text-slate-500">Published 14 March 2026 · 10 minute read</p>
        <p className="mt-6 text-lg leading-8 text-slate-700">ERI’s collaboration with churches, health committees, elders, and youth leaders highlights the powerful role faith-based networks play in safe, dignified community support.</p>
        <div className="mt-8 rounded-3xl border border-slate-200 bg-cream p-6">
          <h2 className="text-xl font-semibold text-navy">Why these partnerships matter</h2>
          <p className="mt-3 text-slate-600">Faith communities often serve as trusted points of contact, helping ERI reach families who might otherwise remain invisible to formal systems.</p>
        </div>
        <div className="mt-8 space-y-8 text-slate-600">
          <section><h2 className="text-2xl font-semibold text-navy">Trust is a practical resource</h2><p className="mt-3 leading-8">For a family facing homelessness, poverty, or conflict, the first barrier is often not a lack of goodwill. It is uncertainty about who can be trusted. Faith communities are already present in many neighborhoods, know local histories, and have relationships that formal services may take longer to establish. Their role can make a first conversation feel safer.</p><p className="mt-3 leading-8">That trust must be handled carefully. A referral should protect privacy, avoid promises that cannot be kept, and give a person a real choice about what happens next. ERI’s partnership model is strongest when faith leaders open a door while trained staff provide the specialist follow-up.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">From referral to coordinated care</h2><p className="mt-3 leading-8">A useful referral is more than passing along a phone number. It includes enough context for the receiving team to understand the immediate concern, the person’s consent, and any urgent safety considerations. Churches, health committees, elders, and youth leaders can help identify those concerns early, then connect people with ERI and other appropriate providers.</p><p className="mt-3 leading-8">Coordination also prevents families from repeating painful stories to many organizations without receiving help. When partners communicate clearly, they can divide responsibilities, reduce duplication, and follow up when a first appointment or referral does not lead to a solution.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">Respecting different roles</h2><p className="mt-3 leading-8">Faith leaders bring moral leadership, pastoral care, and community presence. Health workers bring clinical knowledge. Local elders and youth leaders understand everyday realities and emerging risks. ERI contributes a rehabilitation and reintegration perspective. No single partner should be expected to do all of this work.</p><p className="mt-3 leading-8">Clear boundaries protect both families and partners. Spiritual support can sit alongside professional health, legal, and protection services, but it should not replace them. Likewise, an outreach worker can listen and refer without presenting themselves as a counselor, clinician, or legal adviser when they are not one.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">Including young people and families</h2><p className="mt-3 leading-8">Young people often notice changes in their neighborhoods before formal systems do. Youth leaders can help identify unsafe situations, support positive activities, and make services feel relevant. Families also need space to explain what has happened from their perspective rather than being described only through a problem or crisis.</p><p className="mt-3 leading-8">A family-centered response asks what would make stability possible: documentation, school support, health care, mediation, income opportunities, safer housing, or renewed communication. Partnership becomes meaningful when it helps address those conditions instead of treating one referral as the end of the process.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">Accountability in community work</h2><p className="mt-3 leading-8">Good intentions do not automatically produce safe support. Partners need shared expectations about safeguarding, confidentiality, consent, and how concerns are escalated. They should also be able to say when a referral did not work and review what needs to change.</p><p className="mt-3 leading-8">This kind of accountability strengthens trust rather than weakening it. Families are more likely to return for help when they see that organizations listen to feedback and correct mistakes. It also helps volunteers understand that respectful care is a practice that requires preparation.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">A network that lasts beyond one event</h2><p className="mt-3 leading-8">The goal of faith-based partnership is not to create a single campaign or temporary handover. It is to build a network that notices need earlier, responds with greater coordination, and stays connected through the slower work of rehabilitation. Regular check-ins, shared learning, and reliable points of contact keep that network active.</p><p className="mt-3 leading-8">ERI’s experience shows that community care becomes stronger when trusted local relationships and professional follow-up work together. The result is not a replacement for public services. It is a more connected route into the support people are already entitled to receive.</p></section>
        </div>
        <div className="mt-8">
          <Link href="/news" className="inline-flex rounded-full bg-olive px-5 py-3 font-semibold text-white">Back to news</Link>
        </div>
      </div>
    </main>
  );
}
