"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

type Lang = "en" | "sw" | "fr" | "de" | "es";

type LangContext = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

export const translations: Record<Lang, Record<string, string>> = {
  en: {
    home: "Home",
    about: "About",
    programs: "Programs",
    impact: "Impact",
    get_involved: "Get Involved",
    partners: "Partners",
    news: "News",
    contact: "Contact",
    staff_login: "Staff login",
    donate_now: "Donate now",
    volunteer: "Volunteer",
    join_our_work: "Join our work",
    mission_heading: "Restoring dignity and opening pathways home.",
    page_intro: "ERI Street Initiative works alongside families, government agencies, and local partners in Thika, Mombasa, and Nairobi to support street-connected individuals with identity, care, education, protection, and pathways to livelihoods.",
    hero_tagline: "Community-led rehabilitation for street-connected persons",
    our_approach: "Our approach",
    search_placeholder: "Search pages...",
    search_results: "Showing matching pages",
    no_results: "No matching pages",
    language: "Language",
    english: "English",
    kiswahili: "Kiswahili",
    french: "French",
    german: "German",
    spanish: "Spanish",
    about_title: "Founded in 2023, ERI is building humane pathways for young people and families navigating street life.",
    about_description: "Our work begins with listening. We support each person with practical steps toward legal identity, health care, learning, safety, and lasting livelihoods.",
    mission: "Mission",
    vision: "Vision",
    mission_text: "To restore dignity and transform the lives of street-connected persons through coordinated rehabilitation and strategic partnerships.",
    vision_text: "A Kenya where every person has access to safety, documentation, opportunity, and belonging.",
    values_title: "Our values",
    join_work: "Join our work",
    board: "Board",
    senior_management: "Senior Management",
    programs_title: "A five-stage rehabilitation pathway built for dignity and long-term stability.",
    programs_description: "Each step is designed to be humane, practical, and tailored to the needs of the person we are supporting.",
    impact_title: "Publicly shared progress, grounded in consent and respect.",
    impact_description: "We share aggregate impact data and anonymized stories that reflect the dignity and progress of the people we serve.",
    contact_title: "Reach out for partnerships, referrals, or collaboration.",
    contact_description: "We welcome inquiries from donors, volunteers, families, and community organizations seeking to support our work.",
    get_in_touch: "Get in touch",
    send_message: "Send a message",
    partner_title: "Collaborations that strengthen safety, care, and opportunity.",
    partner_description: "ERI works with public institutions and civil society organizations to expand access to services and create lasting community support.",
    news_title: "Connect with ERI’s progress, milestones, and upcoming partner events.",
    news_description: "Stay updated with our latest news, events, and plans.",
    donate: "Donate",
    start_donation: "Start a test donation",
    preparing_donation: "Preparing your donation checkout...",
    donation_failed: "Checkout could not be started right now.",
    send_message_heading: "Send a message",
    name_placeholder: "Name",
    email_placeholder: "Email",
    message_placeholder: "How can we help?",
    submit: "Submit",
    page_not_found: "Page not found",
    page_not_found_description: "The page you are looking for does not exist, but our mission continues.",
    return_home: "Return home",
    planned: "Planned",
    name: "Name",
    email: "Email",
    message: "Message",
    people_supported: "People supported",
    rehabilitation_stages: "Rehabilitation stages",
    community_partners: "Community partners",
    identity_documents_supported: "Identity documents supported",
    referral_partners: "Referral partners",
    community_volunteers: "Community volunteers",
    our_approach_heading: "Our approach",
    value_dignity: "Dignity",
    value_accountability: "Accountability",
    value_collaboration: "Collaboration",
    value_sustainability: "Sustainability",
    value_compassion: "Compassion",
    value_empowerment: "Empowerment",
    value_trust: "Trust",
    value_community_development: "Community development",
    donation_description: "Support food, health care, school materials, and legal support for people on the path to stability.",
    volunteer_text: "Share your skills in outreach, fundraising, mentoring, or administrative support.",
    sign_up: "Sign up",
    partner_with_us: "Partner with us",
    view_partners: "View partners",
    status_past: "Past events",
    status_upcoming: "Upcoming events",
    status_future: "Future plans",
    no_entries_yet: "No entries yet",
    details_coming_soon: "We are preparing more updates for this category.",
    government: "Government",
    strategic_partner: "Strategic partner",
    health_partner: "Health partner",
  },
  sw: {
    home: "Nyumbani",
    about: "Kuhusu",
    programs: "Programu",
    impact: "Athari",
    get_involved: "Jiunge",
    partners: "Washirika",
    news: "Habari",
    contact: "Wasiliana",
    staff_login: "Ingia wafanyakazi",
    donate_now: "Toa sasa",
    volunteer: "Tajiri",
    join_our_work: "Jiunge na kazi yetu",
    mission_heading: "Kurejesha heshima na kufungua njia za nyumbani.",
    page_intro: "ERI Street Initiative inafanya kazi pamoja na familia, mashirika ya serikali, na washirika wa eneo kusaidia watu walio kwenye mitaa kwa kitambulisho, huduma za afya, elimu, ulinzi, na riziki.",
    our_approach: "Njia yetu",
    search_placeholder: "Tafuta kurasa...",
    search_results: "Inaonyesha kurasa zinazofanana",
    no_results: "Hakuna kurasa zinazofanana",
    language: "Lugha",
    english: "Kiingereza",
    kiswahili: "Kiswahili",
    french: "Kifaransa",
    german: "Kijerumani",
    spanish: "Kihispania",
    about_title: "Imekwishapangwa mwaka 2023, ERI inaweka njia za kibinadamu kwa vijana na familia wanaopitia maisha ya mitaani.",
    about_description: "Kazi yetu inaanza kwa kusikiliza. Tunamsaidia kila mtu kwa hatua za vitendo kuelekea kitambulisho cha kisheria, huduma za afya, elimu, usalama, na riziki ya kudumu.",
    mission: "Dhamira",
    vision: "Maono",
    mission_text: "Kurejesha heshima na kubadilisha maisha ya watu walio kwenye mitaa kupitia urejeshaji ulioratibiwa na ushirikiano wa kimkakati.",
    vision_text: "Kenya ambapo kila mtu ana upatikanaji wa usalama, nyaraka, fursa, na ujumuishwaji.",
    values_title: "Thamani Zetu",
    join_work: "Jiunge na kazi yetu",
    board: "Bodi",
    senior_management: "Usimamizi Mkuu",
    programs_title: "Njia ya hatua tano ya urejeshaji iliyojengwa kwa heshima na utulivu wa muda mrefu.",
    programs_description: "Kila hatua imeundwa iwe ya kibinadamu, ya vitendo, na iliyobadilishwa kwa mahitaji ya mtu tunaemsaidia.",
    impact_title: "Maendeleo ya kushirikiwa kwa uwazi na kwa heshima.",
    impact_description: "Tunashiriki data ya athari kwa ujumla na hadithi zisizo za kibinafsi zinazoonyesha heshima na maendeleo ya watu tunaowaunga.",
    contact_title: "Wasiliana kwa ushirikiano, rufaa, au ushirikiano.",
    contact_description: "Tunakaribisha maswali kutoka kwa wafadhili, wajitolea, familia, na mashirika ya jamii yanayotaka kusaidia kazi yetu.",
    get_in_touch: "Wasiliana nasi",
    send_message: "Tuma ujumbe",
    partner_title: "Ushirikiano unaoongeza usalama, huduma, na fursa.",
    partner_description: "ERI inafanya kazi na taasisi za umma na jamii za kiraia kupanua upatikanaji wa huduma na kuunda msaada wa jamii wa kudumu.",
    news_title: "Ungana na maendeleo ya ERI, hatua, na matukio yajayo ya washirika.",
    news_description: "Baki umejaa taarifa kuhusu habari zetu za hivi karibuni, matukio, na mipango.",
    name: "Jina",
    email: "Barua pepe",
    message: "Ujumbe",
    people_supported: "Watu waliosaidiwa",
    rehabilitation_stages: "Hatua za urejeshaji",
    community_partners: "Washirika wa jamii",
    our_approach_heading: "Njia yetu",
    value_dignity: "Heshima",
    value_accountability: "Uwajibikaji",
    value_collaboration: "Ushirikiano",
    value_sustainability: "Uendelevu",
    value_compassion: "Huruma",
    value_empowerment: "Uwezeshaji",
    value_trust: "Imani",
    value_community_development: "Maendeleo ya jamii",
    volunteer_text: "Shiriki ujuzi wako katika utafutaji wa jamii, ufadhili, uanagenzi, au msaada wa utawala.",
    sign_up: "Jisajili",
    partner_with_us: "Shirikiana nasi",
    view_partners: "Tazama washirika",
    status_past: "Matukio yaliyopita",
    status_upcoming: "Matukio yajayo",
    status_future: "Mipango ya baadaye",
    no_entries_yet: "Hakuna maingizo bado",
    details_coming_soon: "Tunaandaa masasisho zaidi kwa kitengo hiki.",
    hero_tagline: "Rejesha heshima kwa kazi ya jamii kwa watu walio kwenye mitaa",
    identity_documents_supported: "Nyaraka za kitambulisho zilizosaidiwa",
    referral_partners: "Washirika wa rejea",
    community_volunteers: "Wajitolea wa jamii",
    government: "Serikali",
    strategic_partner: "Mshirika wa kimkakati",
    health_partner: "Mshirika wa afya",
    donate: "Toa",
    donation_description: "Tumia chakula, huduma za afya, vifaa vya shule, na msaada wa kisheria kwa watu katika njia ya utulivu.",
    start_donation: "Anzisha malipo ya mtihani",
    preparing_donation: "Tayariweka ununuzi wako wa malipo...",
    donation_failed: "Utaratibu haukuweza kuanzishwa sasa.",
    send_message_heading: "Tuma ujumbe",
    name_placeholder: "Jina",
    email_placeholder: "Barua pepe",
    message_placeholder: "Tutusaidieje?",
    submit: "Tuma",
    page_not_found: "Ukurasa haukupatikana",
    page_not_found_description: "Ukurasa unaotafuta hauupatikani, lakini dhamira yetu inaendelea.",
    return_home: "Rudi nyumbani",
    planned: "Imepangwa",
  },
  fr: {
    home: "Accueil",
    about: "À propos",
    programs: "Programmes",
    impact: "Impact",
    get_involved: "S'impliquer",
    partners: "Partenaires",
    news: "Actualités",
    contact: "Contact",
    staff_login: "Connexion du personnel",
    donate_now: "Faire un don",
    volunteer: "Bénévole",
    join_our_work: "Rejoignez notre travail",
    mission_heading: "Restaurer la dignité et ouvrir des chemins vers la maison.",
    page_intro: "ERI Street Initiative travaille avec des familles, des agences gouvernementales et des partenaires locaux pour soutenir les personnes en situation de rue avec l'identité, les soins, l'éducation, la protection et les moyens de subsistance.",
    our_approach: "Notre approche",
    search_placeholder: "Rechercher des pages...",
    search_results: "Affichage des pages correspondantes",
    no_results: "Aucune page correspondante",
    language: "Langue",
    english: "Anglais",
    kiswahili: "Swahili",
    french: "Français",
    german: "Allemand",
    spanish: "Espagnol",
    about_title: "Fondée en 2023, ERI construit des voies humaines pour les jeunes et les familles confrontés à la vie de rue.",
    about_description: "Notre travail commence par l'écoute. Nous aidons chaque personne avec des étapes concrètes vers l'identité légale, les soins de santé, l'apprentissage, la sécurité et des moyens de subsistance durables.",
    mission: "Mission",
    vision: "Vision",
    mission_text: "Restaurer la dignité et transformer la vie des personnes en situation de rue grâce à une réadaptation coordonnée et des partenariats stratégiques.",
    vision_text: "Une Kenya où chaque personne a accès à la sécurité, à la documentation, aux opportunités et à l'appartenance.",
    values_title: "Nos valeurs",
    join_work: "Rejoignez notre travail",
    board: "Conseil",
    senior_management: "Direction générale",
    programs_title: "Un parcours de réadaptation en cinq étapes conçu pour la dignité et la stabilité à long terme.",
    programs_description: "Chaque étape est conçue pour être humaine, pratique et adaptée aux besoins de la personne que nous soutenons.",
    impact_title: "Progrès partagés publiquement, ancrés dans le consentement et le respect.",
    impact_description: "Nous partageons des données d'impact agrégées et des histoires anonymisées qui reflètent la dignité et les progrès des personnes que nous aidons.",
    contact_title: "Contactez-nous pour des partenariats, des références ou une collaboration.",
    contact_description: "Nous accueillons les demandes des donateurs, des bénévoles, des familles et des organisations communautaires souhaitant soutenir notre travail.",
    get_in_touch: "Contactez-nous",
    send_message: "Envoyer un message",
    partner_title: "Des collaborations qui renforcent la sécurité, les soins et les opportunités.",
    partner_description: "ERI travaille avec des institutions publiques et des organisations de la société civile pour élargir l'accès aux services et créer un soutien communautaire durable.",
    news_title: "Connectez-vous aux progrès, jalons et événements à venir de l'ERI.",
    news_description: "Restez informé de nos dernières nouvelles, événements et plans.",
    name: "Nom",
    email: "Email",
    message: "Message",
    people_supported: "Personnes soutenues",
    rehabilitation_stages: "Étapes de réadaptation",
    community_partners: "Partenaires communautaires",
    our_approach_heading: "Notre approche",
    value_dignity: "Dignité",
    value_accountability: "Responsabilité",
    value_collaboration: "Collaboration",
    value_sustainability: "Durabilité",
    value_compassion: "Compassion",
    value_empowerment: "Autonomisation",
    value_trust: "Confiance",
    value_community_development: "Développement communautaire",
    volunteer_text: "Partagez vos compétences en sensibilisation, collecte de fonds, mentorat ou soutien administratif.",
    sign_up: "Inscrivez-vous",
    partner_with_us: "Partenariat avec nous",
    view_partners: "Voir les partenaires",
    status_past: "Événements passés",
    status_upcoming: "Événements à venir",
    status_future: "Plans futurs",
    no_entries_yet: "Aucune entrée pour le moment",
    details_coming_soon: "Nous préparons plus de mises à jour pour cette catégorie.",
    hero_tagline: "Réhabilitation dirigée par la communauté pour les personnes de rue",
    identity_documents_supported: "Documents d'identité pris en charge",
    referral_partners: "Partenaires de référence",
    community_volunteers: "Bénévoles communautaires",
    government: "Gouvernement",
    strategic_partner: "Partenaire stratégique",
    health_partner: "Partenaire de santé",
    donate: "Faire un don",
    donation_description: "Soutenez la nourriture, les soins de santé, le matériel scolaire et l'aide juridique pour les personnes en voie de stabilité.",
    start_donation: "Démarrer un don de test",
    preparing_donation: "Préparation de votre paiement...",
    donation_failed: "Le processus n'a pas pu être lancé pour le moment.",
    send_message_heading: "Envoyer un message",
    name_placeholder: "Nom",
    email_placeholder: "Email",
    message_placeholder: "Comment pouvons-nous aider ?",
    submit: "Soumettre",
    page_not_found: "Page non trouvée",
    page_not_found_description: "La page que vous recherchez n'existe pas, mais notre mission continue.",
    return_home: "Retour à l'accueil",
    planned: "Planifié",
  },
  de: {
    home: "Startseite",
    about: "Über uns",
    programs: "Programme",
    impact: "Wirkung",
    get_involved: "Mitwirken",
    partners: "Partner",
    news: "News",
    contact: "Kontakt",
    staff_login: "Mitarbeiter anmelden",
    donate_now: "Jetzt spenden",
    volunteer: "Freiwilliger",
    join_our_work: "Arbeiten Sie mit uns",
    mission_heading: "Würde wiederherstellen und Wege nach Hause öffnen.",
    page_intro: "ERI Street Initiative arbeitet mit Familien, Regierungsbehörden und lokalen Partnern zusammen, um obdachlosen Menschen bei Identität, Pflege, Bildung, Schutz und Lebensunterhalt zu helfen.",
    our_approach: "Unser Ansatz",
    search_placeholder: "Seiten durchsuchen...",
    search_results: "Passende Seiten anzeigen",
    no_results: "Keine passenden Seiten",
    language: "Sprache",
    english: "Englisch",
    kiswahili: "Kiswahili",
    french: "Französisch",
    german: "Deutsch",
    spanish: "Spanisch",
    about_title: "Gegründet 2023, baut ERI menschliche Wege für junge Menschen und Familien in der Straße auf.",
    about_description: "Unsere Arbeit beginnt mit Zuhören. Wir unterstützen jede Person mit praktischen Schritten zu rechtlicher Identität, Gesundheitsversorgung, Bildung, Sicherheit und nachhaltigem Lebensunterhalt.",
    mission: "Mission",
    vision: "Vision",
    mission_text: "Würde wiederherstellen und das Leben von Straßenmenschen durch koordinierte Rehabilitation und strategische Partnerschaften transformieren.",
    vision_text: "Ein Kenia, in dem jede Person Zugang zu Sicherheit, Dokumentation, Chancen und Zugehörigkeit hat.",
    values_title: "Unsere Werte",
    join_work: "Arbeiten Sie mit uns",
    board: "Vorstand",
    senior_management: "Geschäftsführung",
    programs_title: "Ein fünfstufiger Rehabilitationsweg, der auf Würde und langfristige Stabilität ausgelegt ist.",
    programs_description: "Jeder Schritt ist darauf ausgelegt, menschlich, praxisnah und auf die Bedürfnisse der von uns unterstützten Person zugeschnitten zu sein.",
    impact_title: "Öffentlich geteilte Fortschritte, die auf Zustimmung und Respekt beruhen.",
    impact_description: "Wir teilen aggregierte Wirkungsdaten und anonymisierte Geschichten, die die Würde und den Fortschritt der von uns unterstützten Menschen widerspiegeln.",
    contact_title: "Kontaktieren Sie uns für Partnerschaften, Überweisungen oder Zusammenarbeit.",
    contact_description: "Wir begrüßen Anfragen von Spendern, Freiwilligen, Familien und Gemeinschaftsorganisationen, die unsere Arbeit unterstützen möchten.",
    get_in_touch: "Nehmen Sie Kontakt auf",
    send_message: "Nachricht senden",
    partner_title: "Zusammenarbeiten, die Sicherheit, Pflege und Chancen stärken.",
    partner_description: "ERI arbeitet mit öffentlichen Institutionen und zivilgesellschaftlichen Organisationen zusammen, um den Zugang zu Dienstleistungen zu erweitern und dauerhafte Gemeinschaftsunterstützung zu schaffen.",
    news_title: "Bleiben Sie verbunden mit ERIs Fortschritten, Meilensteinen und bevorstehenden Partnerveranstaltungen.",
    news_description: "Bleiben Sie über unsere neuesten Nachrichten, Veranstaltungen und Pläne informiert.",
    submit: "Absenden",
    name: "Name",
    email: "E-Mail",
    message: "Nachricht",
    people_supported: "Menschen unterstützt",
    rehabilitation_stages: "Rehabilitationsphasen",
    community_partners: "Gemeinschaftspartner",
    our_approach_heading: "Unser Ansatz",
    value_dignity: "Würde",
    value_accountability: "Verantwortung",
    value_collaboration: "Zusammenarbeit",
    value_sustainability: "Nachhaltigkeit",
    value_compassion: "Mitgefühl",
    value_empowerment: "Ermächtigung",
    value_trust: "Vertrauen",
    value_community_development: "Gemeinschaftsentwicklung",
    donation_description: "Unterstützen Sie Lebensmittel, Gesundheitsversorgung, Schulmaterialien und rechtliche Hilfe für Menschen auf dem Weg zur Stabilität.",
    volunteer_text: "Teilen Sie Ihre Fähigkeiten in Öffentlichkeitsarbeit, Fundraising, Mentoring oder Verwaltungsunterstützung.",
    sign_up: "Anmelden",
    partner_with_us: "Partner werden",
    view_partners: "Partner ansehen",
    status_past: "Vergangene Veranstaltungen",
    status_upcoming: "Kommende Veranstaltungen",
    status_future: "Zukünftige Pläne",
    no_entries_yet: "Noch keine Einträge",
    details_coming_soon: "Wir bereiten weitere Updates für diese Kategorie vor.",
  },
  es: {
    home: "Inicio",
    about: "Acerca",
    programs: "Programas",
    impact: "Impacto",
    get_involved: "Involúcrate",
    partners: "Socios",
    news: "Noticias",
    contact: "Contacto",
    staff_login: "Inicio de sesión personal",
    donate_now: "Donar ahora",
    volunteer: "Voluntario",
    join_our_work: "Únete a nuestro trabajo",
    mission_heading: "Restaurar la dignidad y abrir caminos a casa.",
    page_intro: "ERI Street Initiative trabaja con familias, agencias gubernamentales y socios locales para apoyar a personas en situación de calle con identidad, atención, educación, protección y medios de vida.",
    our_approach: "Nuestro enfoque",
    search_placeholder: "Buscar páginas...",
    search_results: "Mostrando páginas coincidentes",
    no_results: "No hay páginas coincidentes",
    language: "Idioma",
    english: "Inglés",
    kiswahili: "Kiswahili",
    french: "Francés",
    german: "Alemán",
    spanish: "Español",
    about_title: "Fundada en 2023, ERI está construyendo caminos humanos para jóvenes y familias que navegan la vida en la calle.",
    about_description: "Nuestro trabajo comienza con la escucha. Apoyamos a cada persona con pasos prácticos hacia la identidad legal, la atención médica, el aprendizaje, la seguridad y medios de vida duraderos.",
    mission: "Misión",
    vision: "Visión",
    mission_text: "Restaurar la dignidad y transformar las vidas de las personas en situación de calle a través de rehabilitación coordinada y asociaciones estratégicas.",
    vision_text: "Un Kenia donde cada persona tenga acceso a seguridad, documentación, oportunidades y pertenencia.",
    values_title: "Nuestros valores",
    join_work: "Únete a nuestro trabajo",
    board: "Consejo",
    senior_management: "Alta dirección",
    programs_title: "Una ruta de rehabilitación de cinco etapas construida para la dignidad y la estabilidad a largo plazo.",
    programs_description: "Cada paso está diseñado para ser humano, práctico y adaptado a las necesidades de la persona a la que apoyamos.",
    impact_title: "Progreso compartido públicamente, basado en el consentimiento y el respeto.",
    impact_description: "Compartimos datos agregados de impacto e historias anonimizadas que reflejan la dignidad y el progreso de las personas a las que servimos.",
    contact_title: "Comuníquese para colaboraciones, referencias o trabajo conjunto.",
    contact_description: "Damos la bienvenida a consultas de donantes, voluntarios, familias y organizaciones comunitarias que desean apoyar nuestro trabajo.",
    get_in_touch: "Ponte en contacto",
    send_message: "Enviar mensaje",
    partner_title: "Colaboraciones que fortalecen la seguridad, la atención y las oportunidades.",
    partner_description: "ERI trabaja con instituciones públicas y organizaciones de la sociedad civil para ampliar el acceso a servicios y crear apoyo comunitario duradero.",
    news_title: "Conéctate con los avances, hitos y eventos futuros de ERI.",
    news_description: "Mantente al día con nuestras últimas noticias, eventos y planes.",
    name: "Nombre",
    email: "Correo electrónico",
    message: "Mensaje",
    people_supported: "Personas apoyadas",
    rehabilitation_stages: "Etapas de rehabilitación",
    community_partners: "Socios comunitarios",
    our_approach_heading: "Nuestro enfoque",
    value_dignity: "Dignidad",
    value_accountability: "Responsabilidad",
    value_collaboration: "Colaboración",
    value_sustainability: "Sostenibilidad",
    value_compassion: "Compasión",
    value_empowerment: "Empoderamiento",
    value_trust: "Confianza",
    value_community_development: "Desarrollo comunitario",
    volunteer_text: "Comparte tus habilidades en divulgación, recaudación de fondos, mentoría o apoyo administrativo.",
    sign_up: "Regístrate",
    partner_with_us: "Asóciate con nosotros",
    view_partners: "Ver socios",
    status_past: "Eventos pasados",
    status_upcoming: "Eventos próximos",
    status_future: "Planes futuros",
    no_entries_yet: "Aún no hay entradas",
    details_coming_soon: "Estamos preparando más actualizaciones para esta categoría.",
    hero_tagline: "Rehabilitación liderada por la comunidad para personas en situación de calle",
    identity_documents_supported: "Documentos de identidad respaldados",
    referral_partners: "Socios de referencia",
    community_volunteers: "Voluntarios comunitarios",
    government: "Gobierno",
    strategic_partner: "Socio estratégico",
    health_partner: "Socio de salud",
    donate: "Donar",
    donation_description: "Apoya alimentos, atención médica, materiales escolares y asistencia legal para personas en camino hacia la estabilidad.",
    start_donation: "Iniciar una donación de prueba",
    preparing_donation: "Preparando su pago...",
    donation_failed: "No se pudo iniciar el proceso ahora mismo.",
    send_message_heading: "Enviar un mensaje",
    name_placeholder: "Nombre",
    email_placeholder: "Correo electrónico",
    message_placeholder: "¿Cómo podemos ayudar?",
    submit: "Enviar",
    page_not_found: "Página no encontrada",
    page_not_found_description: "La página que busca no existe, pero nuestra misión continúa.",
    return_home: "Volver al inicio",
    planned: "Planeado",
  },
};

const LanguageContext = createContext<LangContext | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    return (localStorage.getItem("eri_lang") as Lang) || "en";
  });

  useEffect(() => {
    localStorage.setItem("eri_lang", lang);
  }, [lang]);

  function setLang(l: Lang) {
    setLangState(l);
  }

  function t(key: string) {
    return translations[lang][key] ?? translations.en[key] ?? key;
  }

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export default LanguageProvider;
