"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

type Lang = "en" | "sw" | "fr" | "de" | "es";

type LangContext = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

export const translations: Record<Lang, Record<string, string>> = {
  en: {
    back_to_get_involved: "Back to Get Involved",
    home: "Home",
    about: "About",
    programs: "Programs",
    impact: "Impact",
    get_involved: "Get Involved",
    partners: "Partners",
    news: "News",
    contact: "Contact",
    staff_login: "Staff login",
    donate_now: "Donate now",
    volunteer: "Volunteer",
    join_our_work: "Join our work",
    mission_heading: "Restoring dignity and opening pathways home.",
    page_intro: "ERI Street Initiative works alongside families, government agencies, and local partners in Thika, Mombasa, and Nairobi to support street-connected individuals with identity, care, education, protection, and pathways to livelihoods.",
    hero_tagline: "Community-led rehabilitation for street-connected persons",
    our_approach: "Our approach",
    search_placeholder: "Search pages...",
    search_results: "Showing matching pages",
    no_results: "No matching pages",
    language: "Language",
    english: "English",
    kiswahili: "Kiswahili",
    french: "French",
    german: "German",
    spanish: "Spanish",
    about_title: "Founded in 2023, ERI is building humane pathways for young people and families navigating street life.",
    about_description: "Our work begins with listening. We support each person with practical steps toward legal identity, health care, learning, safety, and lasting livelihoods.",
    mission: "Mission",
    vision: "Vision",
    mission_text: "To restore dignity and transform the lives of street-connected persons through coordinated rehabilitation and strategic partnerships.",
    vision_text: "A Kenya where every person has access to safety, documentation, opportunity, and belonging.",
    values_title: "Our values",
    join_work: "Join our work",
    board: "Board",
    senior_management: "Senior Management",
    programs_title: "A five-stage rehabilitation pathway built for dignity and long-term stability.",
    programs_description: "Each step is designed to be humane, practical, and tailored to the needs of the person we are supporting.",
    impact_title: "Publicly shared progress, grounded in consent and respect.",
    impact_description: "We share aggregate impact data and anonymized stories that reflect the dignity and progress of the people we serve.",
    contact_title: "Reach out for partnerships, referrals, or collaboration.",
    contact_description: "We welcome inquiries from donors, volunteers, families, and community organizations seeking to support our work.",
    get_in_touch: "Get in touch",
    send_message: "Send a message",
    partner_title: "Collaborations that strengthen safety, care, and opportunity.",
    partner_description: "ERI works with public institutions and civil society organizations to expand access to services and create lasting community support.",
    news_title: "Connect with ERI’s progress, milestones, and upcoming partner events.",
    news_description: "Stay updated with our latest news, events, and plans.",
    donate: "Donate",
    start_donation: "Start a test donation",
    preparing_donation: "Preparing your donation checkout...",
    donation_failed: "Checkout could not be started right now.",
    send_message_heading: "Send a message",
    name_placeholder: "Name",
    email_placeholder: "Email",
    message_placeholder: "How can we help?",
    submit: "Submit",
    page_not_found: "Page not found",
    page_not_found_description: "The page you are looking for does not exist, but our mission continues.",
    return_home: "Return home",
    planned: "Planned",
    name: "Name",
    email: "Email",
    message: "Message",
    people_supported: "People supported",
    rehabilitation_stages: "Rehabilitation stages",
    community_partners: "Community partners",
    identity_documents_supported: "Identity documents supported",
    referral_partners: "Referral partners",
    community_volunteers: "Community volunteers",
    our_approach_heading: "Our approach",
    value_dignity: "Dignity",
    value_accountability: "Accountability",
    value_collaboration: "Collaboration",
    value_sustainability: "Sustainability",
    value_compassion: "Compassion",
    value_empowerment: "Empowerment",
    value_trust: "Trust",
    value_community_development: "Community development",
    donation_description: "Support food, health care, school materials, and legal support for people on the path to stability.",
    volunteer_text: "Share your skills in outreach, fundraising, mentoring, or administrative support.",
    sign_up: "Sign up",
    partner_with_us: "Partner with us",
    view_partners: "View partners",
    status_past: "Past events",
    status_upcoming: "Upcoming events",
    status_future: "Future plans",
    no_entries_yet: "No entries yet",
    details_coming_soon: "We are preparing more updates for this category.",
    government: "Government",
    strategic_partner: "Strategic partner",
    health_partner: "Health partner",
    events: "Events",
    events_title: "ERI events calendar: upcoming, past, and future impact moments.",
    read_more: "Read more",
    learn_more: "Learn more",
    highlights: "Highlights",
    our_work: "Our work",
    supporting_communities: "Supporting communities with practical action and care",
    featured_programs: "Featured programs",
    programs_that_deepen_outreach: "Programs that deepen outreach and long-term support",
    flagship_initiatives: "Flagship initiatives",
    coastal_resilience: "Coastal resilience",
    local_solutions: "Local solutions that protect people and ecosystems",
    learn_more_short: "Learn more",
    journey_highlight: "Journey highlight",
    our_journey: "Our journey",
    open_gallery: "Open gallery",
    close: "Close",
    collaboration_strengthens_community_care: "Collaboration that strengthens community care",
    partners_intro: "ERI works through a wide network of partners, faith communities, and frontline volunteers to make outreach more trusted, more responsive, and more sustainable.",
    ambassadors_strengthen_trust: "Ambassadors strengthen trust",
    faith_based_collaboration: "Faith-based collaboration",
    partner_led_referrals: "Partner-led referrals",
    faith_based_and_community_partnerships: "Faith-based and community partnerships",
    why_partnerships_matter: "Why these partnerships matter",
    partners_tag: "Partners",
    timeline_eri_founded: "ERI founded",
    timeline_thika_food_drive: "Thika Food Drive",
    timeline_mombasa_food_drive: "Mombasa Food Drive",
    timeline_juja_farm_food_drive: "Juja Farm Food Drive",
    timeline_mlango_kubwa_food_drive: "Mlango Kubwa Food Drive",
    timeline_expansion_onboarding: "Organizational expansion and onboarding",
  },
  sw: {
    back_to_get_involved: "Rudi kwenye Jiunge",
    home: "Nyumbani",
    about: "Kuhusu",
    programs: "Programu",
    impact: "Athari",
    get_involved: "Jiunge",
    partners: "Washirika",
    news: "Habari",
    contact: "Wasiliana",
    staff_login: "Ingia wafanyakazi",
    donate_now: "Toa sasa",
    volunteer: "Tajiri",
    join_our_work: "Jiunge na kazi yetu",
    mission_heading: "Kurejesha heshima na kufungua njia za nyumbani.",
    page_intro: "ERI Street Initiative inafanya kazi pamoja na familia, mashirika ya serikali, na washirika wa eneo kusaidia watu walio kwenye mitaa kwa kitambulisho, huduma za afya, elimu, ulinzi, na riziki.",
    our_approach: "Njia yetu",
    search_placeholder: "Tafuta kurasa...",
    search_results: "Inaonyesha kurasa zinazofanana",
    no_results: "Hakuna kurasa zinazofanana",
    language: "Lugha",
    english: "Kiingereza",
    kiswahili: "Kiswahili",
    french: "Kifaransa",
    german: "Kijerumani",
    spanish: "Kihispania",
    about_title: "Imekwishapangwa mwaka 2023, ERI inaweka njia za kibinadamu kwa vijana na familia wanaopitia maisha ya mitaani.",
    about_description: "Kazi yetu inaanza kwa kusikiliza. Tunamsaidia kila mtu kwa hatua za vitendo kuelekea kitambulisho cha kisheria, huduma za afya, elimu, usalama, na riziki ya kudumu.",
    mission: "Dhamira",
    vision: "Maono",
    mission_text: "Kurejesha heshima na kubadilisha maisha ya watu walio kwenye mitaa kupitia urejeshaji ulioratibiwa na ushirikiano wa kimkakati.",
    vision_text: "Kenya ambapo kila mtu ana upatikanaji wa usalama, nyaraka, fursa, na ujumuishwaji.",
    values_title: "Thamani Zetu",
    join_work: "Jiunge na kazi yetu",
    board: "Bodi",
    senior_management: "Usimamizi Mkuu",
    programs_title: "Njia ya hatua tano ya urejeshaji iliyojengwa kwa heshima na utulivu wa muda mrefu.",
    programs_description: "Kila hatua imeundwa iwe ya kibinadamu, ya vitendo, na iliyobadilishwa kwa mahitaji ya mtu tunaemsaidia.",
    impact_title: "Maendeleo ya kushirikiwa kwa uwazi na kwa heshima.",
    impact_description: "Tunashiriki data ya athari kwa ujumla na hadithi zisizo za kibinafsi zinazoonyesha heshima na maendeleo ya watu tunaowaunga.",
    contact_title: "Wasiliana kwa ushirikiano, rufaa, au ushirikiano.",
    contact_description: "Tunakaribisha maswali kutoka kwa wafadhili, wajitolea, familia, na mashirika ya jamii yanayotaka kusaidia kazi yetu.",
    get_in_touch: "Wasiliana nasi",
    send_message: "Tuma ujumbe",
    partner_title: "Ushirikiano unaoongeza usalama, huduma, na fursa.",
    partner_description: "ERI inafanya kazi na taasisi za umma na jamii za kiraia kupanua upatikanaji wa huduma na kuunda msaada wa jamii wa kudumu.",
    news_title: "Ungana na maendeleo ya ERI, hatua, na matukio yajayo ya washirika.",
    news_description: "Baki umejaa taarifa kuhusu habari zetu za hivi karibuni, matukio, na mipango.",
    name: "Jina",
    email: "Barua pepe",
    message: "Ujumbe",
    people_supported: "Watu waliosaidiwa",
    rehabilitation_stages: "Hatua za urejeshaji",
    community_partners: "Washirika wa jamii",
    our_approach_heading: "Njia yetu",
    value_dignity: "Heshima",
    value_accountability: "Uwajibikaji",
    value_collaboration: "Ushirikiano",
    value_sustainability: "Uendelevu",
    value_compassion: "Huruma",
    value_empowerment: "Uwezeshaji",
    value_trust: "Imani",
    value_community_development: "Maendeleo ya jamii",
    volunteer_text: "Shiriki ujuzi wako katika utafutaji wa jamii, ufadhili, uanagenzi, au msaada wa utawala.",
    sign_up: "Jisajili",
    partner_with_us: "Shirikiana nasi",
    view_partners: "Tazama washirika",
    status_past: "Matukio yaliyopita",
    status_upcoming: "Matukio yajayo",
    status_future: "Mipango ya baadaye",
    no_entries_yet: "Hakuna maingizo bado",
    details_coming_soon: "Tunaandaa masasisho zaidi kwa kitengo hiki.",
    hero_tagline: "Rejesha heshima kwa kazi ya jamii kwa watu walio kwenye mitaa",
    identity_documents_supported: "Nyaraka za kitambulisho zilizosaidiwa",
    referral_partners: "Washirika wa rejea",
    community_volunteers: "Wajitolea wa jamii",
    government: "Serikali",
    strategic_partner: "Mshirika wa kimkakati",
    health_partner: "Mshirika wa afya",
    donate: "Toa",
    donation_description: "Tumia chakula, huduma za afya, vifaa vya shule, na msaada wa kisheria kwa watu katika njia ya utulivu.",
    start_donation: "Anzisha malipo ya mtihani",
    preparing_donation: "Tayariweka ununuzi wako wa malipo...",
    donation_failed: "Utaratibu haukuweza kuanzishwa sasa.",
    send_message_heading: "Tuma ujumbe",
    name_placeholder: "Jina",
    email_placeholder: "Barua pepe",
    message_placeholder: "Tutusaidieje?",
    submit: "Tuma",
    page_not_found: "Ukurasa haukupatikana",
    page_not_found_description: "Ukurasa unaotafuta hauupatikani, lakini dhamira yetu inaendelea.",
    return_home: "Rudi nyumbani",
    planned: "Imepangwa",
    events: "Matukio",
    events_title: "Kalenda ya matukio ya ERI: yajayo, yaliyopita, na nyakati za athari ya baadaye.",
    read_more: "Soma zaidi",
    learn_more: "Jifunze zaidi",
    highlights: "Viwango",
    our_work: "Kazi yetu",
    supporting_communities: "Kusaidia jamii kwa hatua na huduma za vitendo",
    featured_programs: "Programu zinazotambulika",
    programs_that_deepen_outreach: "Programu zinazozidi kufikisha huduma na msaada wa muda mrefu",
    flagship_initiatives: "Mipango ya kipekee",
    coastal_resilience: "Uimara wa pwani",
    local_solutions: "Ufumbuzi wa ndani unaolinda watu na mazingira",
    learn_more_short: "Jifunze zaidi",
    journey_highlight: "Mwangaza wa safari",
    our_journey: "Safari yetu",
    open_gallery: "Fungua picha",
    close: "Funga",
    collaboration_strengthens_community_care: "Ushirikiano unaosaidia huduma ya jamii",
    partners_intro: "ERI inafanya kazi kupitia mtandao mpana wa washirika, jumuiya za imani, na wajitolea wa hatua za kwanza ili kufanya huduma kuwa ya kuaminika, yenye majibu, na endelevu.",
    ambassadors_strengthen_trust: "Wawakilishi wa mitaani wanaongeza imani",
    faith_based_collaboration: "Ushirikiano wa imani",
    partner_led_referrals: "Rufaa zinazoongozwa na washirika",
    faith_based_and_community_partnerships: "Ushirikiano wa imani na jamii",
    why_partnerships_matter: "Kwa nini ushirikiano huu ni muhimu",
    partners_tag: "Washirika",
    timeline_eri_founded: "ERI ilianzishwa",
    timeline_thika_food_drive: "Gari la chakula la Thika",
    timeline_mombasa_food_drive: "Gari la chakula la Mombasa",
    timeline_juja_farm_food_drive: "Gari la chakula la Juja Farm",
    timeline_expansion_onboarding: "Upanuzi wa shirika na upokeaji wa wanachama",
  },
  fr: {
    back_to_get_involved: "Retour à S'impliquer",
    home: "Accueil",
    about: "À propos",
    programs: "Programmes",
    impact: "Impact",
    get_involved: "S'impliquer",
    partners: "Partenaires",
    news: "Actualités",
    contact: "Contact",
    staff_login: "Connexion du personnel",
    donate_now: "Faire un don",
    volunteer: "Bénévole",
    join_our_work: "Rejoignez notre travail",
    mission_heading: "Restaurer la dignité et ouvrir des chemins vers la maison.",
    page_intro: "ERI Street Initiative travaille avec des familles, des agences gouvernementales et des partenaires locaux pour soutenir les personnes en situation de rue avec l'identité, les soins, l'éducation, la protection et les moyens de subsistance.",
    our_approach: "Notre approche",
    search_placeholder: "Rechercher des pages...",
    search_results: "Affichage des pages correspondantes",
    no_results: "Aucune page correspondante",
    language: "Langue",
    english: "Anglais",
    kiswahili: "Swahili",
    french: "Français",
    german: "Allemand",
    spanish: "Espagnol",
    about_title: "Fondée en 2023, ERI construit des voies humaines pour les jeunes et les familles confrontés à la vie de rue.",
    about_description: "Notre travail commence par l'écoute. Nous aidons chaque personne avec des étapes concrètes vers l'identité légale, les soins de santé, l'apprentissage, la sécurité et des moyens de subsistance durables.",
    mission: "Mission",
    vision: "Vision",
    mission_text: "Restaurer la dignité et transformer la vie des personnes en situation de rue grâce à une réadaptation coordonnée et des partenariats stratégiques.",
    vision_text: "Une Kenya où chaque personne a accès à la sécurité, à la documentation, aux opportunités et à l'appartenance.",
    values_title: "Nos valeurs",
    join_work: "Rejoignez notre travail",
    board: "Conseil",
    senior_management: "Direction générale",
    programs_title: "Un parcours de réadaptation en cinq étapes conçu pour la dignité et la stabilité à long terme.",
    programs_description: "Chaque étape est conçue pour être humaine, pratique et adaptée aux besoins de la personne que nous soutenons.",
    impact_title: "Progrès partagés publiquement, ancrés dans le consentement et le respect.",
    impact_description: "Nous partageons des données d'impact agrégées et des histoires anonymisées qui reflètent la dignité et les progrès des personnes que nous aidons.",
    contact_title: "Contactez-nous pour des partenariats, des références ou une collaboration.",
    contact_description: "Nous accueillons les demandes des donateurs, des bénévoles, des familles et des organisations communautaires souhaitant soutenir notre travail.",
    get_in_touch: "Contactez-nous",
    send_message: "Envoyer un message",
    partner_title: "Des collaborations qui renforcent la sécurité, les soins et les opportunités.",
    partner_description: "ERI travaille avec des institutions publiques et des organisations de la société civile pour élargir l'accès aux services et créer un soutien communautaire durable.",
    news_title: "Connectez-vous aux progrès, jalons et événements à venir de l'ERI.",
    news_description: "Restez informé de nos dernières nouvelles, événements et plans.",
    name: "Nom",
    email: "Email",
    message: "Message",
    people_supported: "Personnes soutenues",
    rehabilitation_stages: "Étapes de réadaptation",
    community_partners: "Partenaires communautaires",
    our_approach_heading: "Notre approche",
    value_dignity: "Dignité",
    value_accountability: "Responsabilité",
    value_collaboration: "Collaboration",
    value_sustainability: "Durabilité",
    value_compassion: "Compassion",
    value_empowerment: "Autonomisation",
    value_trust: "Confiance",
    value_community_development: "Développement communautaire",
    volunteer_text: "Partagez vos compétences en sensibilisation, collecte de fonds, mentorat ou soutien administratif.",
    sign_up: "Inscrivez-vous",
    partner_with_us: "Partenariat avec nous",
    view_partners: "Voir les partenaires",
    status_past: "Événements passés",
    status_upcoming: "Événements à venir",
    status_future: "Plans futurs",
    no_entries_yet: "Aucune entrée pour le moment",
    details_coming_soon: "Nous préparons plus de mises à jour pour cette catégorie.",
    hero_tagline: "Réhabilitation dirigée par la communauté pour les personnes de rue",
    identity_documents_supported: "Documents d'identité pris en charge",
    referral_partners: "Partenaires de référence",
    community_volunteers: "Bénévoles communautaires",
    government: "Gouvernement",
    strategic_partner: "Partenaire stratégique",
    health_partner: "Partenaire de santé",
    donate: "Faire un don",
    donation_description: "Soutenez la nourriture, les soins de santé, le matériel scolaire et l'aide juridique pour les personnes en voie de stabilité.",
    start_donation: "Démarrer un don de test",
    preparing_donation: "Préparation de votre paiement...",
    donation_failed: "Le processus n'a pas pu être lancé pour le moment.",
    send_message_heading: "Envoyer un message",
    name_placeholder: "Nom",
    email_placeholder: "Email",
    message_placeholder: "Comment pouvons-nous aider ?",
    submit: "Soumettre",
    page_not_found: "Page non trouvée",
    page_not_found_description: "La page que vous recherchez n'existe pas, mais notre mission continue.",
    return_home: "Retour à l'accueil",
    planned: "Planifié",
    events: "Événements",
    events_title: "Calendrier des événements ERI : à venir, passés et moments d'impact futurs.",
    read_more: "Lire la suite",
    learn_more: "En savoir plus",
    highlights: "Points forts",
    our_work: "Notre travail",
    supporting_communities: "Soutenir les communautés avec des actions et des soins concrets",
    featured_programs: "Programmes phares",
    programs_that_deepen_outreach: "Programmes qui renforcent la portée et le soutien à long terme",
    flagship_initiatives: "Initiatives phares",
    coastal_resilience: "Résilience côtière",
    local_solutions: "Solutions locales qui protègent les personnes et les écosystèmes",
    learn_more_short: "En savoir plus",
    journey_highlight: "Point fort du parcours",
    our_journey: "Notre parcours",
    open_gallery: "Ouvrir la galerie",
    close: "Fermer",
    collaboration_strengthens_community_care: "Une collaboration qui renforce les soins communautaires",
    partners_intro: "ERI travaille à travers un vaste réseau de partenaires, de communautés de foi et de bénévoles de terrain pour rendre la sensibilisation plus fiable, plus réactive et plus durable.",
    ambassadors_strengthen_trust: "Les ambassadeurs renforcent la confiance",
    faith_based_collaboration: "Collaboration de foi",
    partner_led_referrals: "Orientations menées par les partenaires",
    faith_based_and_community_partnerships: "Partenariats communautaires et de foi",
    why_partnerships_matter: "Pourquoi ces partenariats comptent",
    partners_tag: "Partenaires",
  },
  de: {
    back_to_get_involved: "Zurück zu Mitwirken",
    home: "Startseite",
    about: "Über uns",
    programs: "Programme",
    impact: "Wirkung",
    get_involved: "Mitwirken",
    partners: "Partner",
    news: "News",
    contact: "Kontakt",
    staff_login: "Mitarbeiter anmelden",
    donate_now: "Jetzt spenden",
    volunteer: "Freiwilliger",
    join_our_work: "Arbeiten Sie mit uns",
    mission_heading: "Würde wiederherstellen und Wege nach Hause öffnen.",
    page_intro: "ERI Street Initiative arbeitet mit Familien, Regierungsbehörden und lokalen Partnern zusammen, um obdachlosen Menschen bei Identität, Pflege, Bildung, Schutz und Lebensunterhalt zu helfen.",
    our_approach: "Unser Ansatz",
    search_placeholder: "Seiten durchsuchen...",
    search_results: "Passende Seiten anzeigen",
    no_results: "Keine passenden Seiten",
    language: "Sprache",
    english: "Englisch",
    kiswahili: "Kiswahili",
    french: "Französisch",
    german: "Deutsch",
    spanish: "Spanisch",
    about_title: "Gegründet 2023, baut ERI menschliche Wege für junge Menschen und Familien in der Straße auf.",
    about_description: "Unsere Arbeit beginnt mit Zuhören. Wir unterstützen jede Person mit praktischen Schritten zu rechtlicher Identität, Gesundheitsversorgung, Bildung, Sicherheit und nachhaltigem Lebensunterhalt.",
    mission: "Mission",
    vision: "Vision",
    mission_text: "Würde wiederherstellen und das Leben von Straßenmenschen durch koordinierte Rehabilitation und strategische Partnerschaften transformieren.",
    vision_text: "Ein Kenia, in dem jede Person Zugang zu Sicherheit, Dokumentation, Chancen und Zugehörigkeit hat.",
    values_title: "Unsere Werte",
    join_work: "Arbeiten Sie mit uns",
    board: "Vorstand",
    senior_management: "Geschäftsführung",
    programs_title: "Ein fünfstufiger Rehabilitationsweg, der auf Würde und langfristige Stabilität ausgelegt ist.",
    programs_description: "Jeder Schritt ist darauf ausgelegt, menschlich, praxisnah und auf die Bedürfnisse der von uns unterstützten Person zugeschnitten zu sein.",
    impact_title: "Öffentlich geteilte Fortschritte, die auf Zustimmung und Respekt beruhen.",
    impact_description: "Wir teilen aggregierte Wirkungsdaten und anonymisierte Geschichten, die die Würde und den Fortschritt der von uns unterstützten Menschen widerspiegeln.",
    contact_title: "Kontaktieren Sie uns für Partnerschaften, Überweisungen oder Zusammenarbeit.",
    contact_description: "Wir begrüßen Anfragen von Spendern, Freiwilligen, Familien und Gemeinschaftsorganisationen, die unsere Arbeit unterstützen möchten.",
    get_in_touch: "Nehmen Sie Kontakt auf",
    send_message: "Nachricht senden",
    partner_title: "Zusammenarbeiten, die Sicherheit, Pflege und Chancen stärken.",
    partner_description: "ERI arbeitet mit öffentlichen Institutionen und zivilgesellschaftlichen Organisationen zusammen, um den Zugang zu Dienstleistungen zu erweitern und dauerhafte Gemeinschaftsunterstützung zu schaffen.",
    news_title: "Bleiben Sie verbunden mit ERIs Fortschritten, Meilensteinen und bevorstehenden Partnerveranstaltungen.",
    news_description: "Bleiben Sie über unsere neuesten Nachrichten, Veranstaltungen und Pläne informiert.",
    submit: "Absenden",
    name: "Name",
    email: "E-Mail",
    message: "Nachricht",
    people_supported: "Menschen unterstützt",
    rehabilitation_stages: "Rehabilitationsphasen",
    community_partners: "Gemeinschaftspartner",
    our_approach_heading: "Unser Ansatz",
    value_dignity: "Würde",
    value_accountability: "Verantwortung",
    value_collaboration: "Zusammenarbeit",
    value_sustainability: "Nachhaltigkeit",
    value_compassion: "Mitgefühl",
    value_empowerment: "Ermächtigung",
    value_trust: "Vertrauen",
    value_community_development: "Gemeinschaftsentwicklung",
    donation_description: "Unterstützen Sie Lebensmittel, Gesundheitsversorgung, Schulmaterialien und rechtliche Hilfe für Menschen auf dem Weg zur Stabilität.",
    volunteer_text: "Teilen Sie Ihre Fähigkeiten in Öffentlichkeitsarbeit, Fundraising, Mentoring oder Verwaltungsunterstützung.",
    sign_up: "Anmelden",
    partner_with_us: "Partner werden",
    view_partners: "Partner ansehen",
    status_past: "Vergangene Veranstaltungen",
    status_upcoming: "Kommende Veranstaltungen",
    status_future: "Zukünftige Pläne",
    no_entries_yet: "Noch keine Einträge",
    details_coming_soon: "Wir bereiten weitere Updates für diese Kategorie vor.",
  },
  es: {
    back_to_get_involved: "Volver a Involúcrate",
    home: "Inicio",
    about: "Acerca",
    programs: "Programas",
    impact: "Impacto",
    get_involved: "Involúcrate",
    partners: "Socios",
    news: "Noticias",
    contact: "Contacto",
    staff_login: "Inicio de sesión personal",
    donate_now: "Donar ahora",
    volunteer: "Voluntario",
    join_our_work: "Únete a nuestro trabajo",
    mission_heading: "Restaurar la dignidad y abrir caminos a casa.",
    page_intro: "ERI Street Initiative trabaja con familias, agencias gubernamentales y socios locales para apoyar a personas en situación de calle con identidad, atención, educación, protección y medios de vida.",
    our_approach: "Nuestro enfoque",
    search_placeholder: "Buscar páginas...",
    search_results: "Mostrando páginas coincidentes",
    no_results: "No hay páginas coincidentes",
    language: "Idioma",
    english: "Inglés",
    kiswahili: "Kiswahili",
    french: "Francés",
    german: "Alemán",
    spanish: "Español",
    about_title: "Fundada en 2023, ERI está construyendo caminos humanos para jóvenes y familias que navegan la vida en la calle.",
    about_description: "Nuestro trabajo comienza con la escucha. Apoyamos a cada persona con pasos prácticos hacia la identidad legal, la atención médica, el aprendizaje, la seguridad y medios de vida duraderos.",
    mission: "Misión",
    vision: "Visión",
    mission_text: "Restaurar la dignidad y transformar las vidas de las personas en situación de calle a través de rehabilitación coordinada y asociaciones estratégicas.",
    vision_text: "Un Kenia donde cada persona tenga acceso a seguridad, documentación, oportunidades y pertenencia.",
    values_title: "Nuestros valores",
    join_work: "Únete a nuestro trabajo",
    board: "Consejo",
    senior_management: "Alta dirección",
    programs_title: "Una ruta de rehabilitación de cinco etapas construida para la dignidad y la estabilidad a largo plazo.",
    programs_description: "Cada paso está diseñado para ser humano, práctico y adaptado a las necesidades de la persona a la que apoyamos.",
    impact_title: "Progreso compartido públicamente, basado en el consentimiento y el respeto.",
    impact_description: "Compartimos datos agregados de impacto e historias anonimizadas que reflejan la dignidad y el progreso de las personas a las que servimos.",
    contact_title: "Comuníquese para colaboraciones, referencias o trabajo conjunto.",
    contact_description: "Damos la bienvenida a consultas de donantes, voluntarios, familias y organizaciones comunitarias que desean apoyar nuestro trabajo.",
    get_in_touch: "Ponte en contacto",
    send_message: "Enviar mensaje",
    partner_title: "Colaboraciones que fortalecen la seguridad, la atención y las oportunidades.",
    partner_description: "ERI trabaja con instituciones públicas y organizaciones de la sociedad civil para ampliar el acceso a servicios y crear apoyo comunitario duradero.",
    news_title: "Conéctate con los avances, hitos y eventos futuros de ERI.",
    news_description: "Mantente al día con nuestras últimas noticias, eventos y planes.",
    name: "Nombre",
    email: "Correo electrónico",
    message: "Mensaje",
    people_supported: "Personas apoyadas",
    rehabilitation_stages: "Etapas de rehabilitación",
    community_partners: "Socios comunitarios",
    our_approach_heading: "Nuestro enfoque",
    value_dignity: "Dignidad",
    value_accountability: "Responsabilidad",
    value_collaboration: "Colaboración",
    value_sustainability: "Sostenibilidad",
    value_compassion: "Compasión",
    value_empowerment: "Empoderamiento",
    value_trust: "Confianza",
    value_community_development: "Desarrollo comunitario",
    volunteer_text: "Comparte tus habilidades en divulgación, recaudación de fondos, mentoría o apoyo administrativo.",
    sign_up: "Regístrate",
    partner_with_us: "Asóciate con nosotros",
    view_partners: "Ver socios",
    status_past: "Eventos pasados",
    status_upcoming: "Eventos próximos",
    status_future: "Planes futuros",
    no_entries_yet: "Aún no hay entradas",
    details_coming_soon: "Estamos preparando más actualizaciones para esta categoría.",
    hero_tagline: "Rehabilitación liderada por la comunidad para personas en situación de calle",
    identity_documents_supported: "Documentos de identidad respaldados",
    referral_partners: "Socios de referencia",
    community_volunteers: "Voluntarios comunitarios",
    government: "Gobierno",
    strategic_partner: "Socio estratégico",
    health_partner: "Socio de salud",
    donate: "Donar",
    donation_description: "Apoya alimentos, atención médica, materiales escolares y asistencia legal para personas en camino hacia la estabilidad.",
    start_donation: "Iniciar una donación de prueba",
    preparing_donation: "Preparando su pago...",
    donation_failed: "No se pudo iniciar el proceso ahora mismo.",
    send_message_heading: "Enviar un mensaje",
    name_placeholder: "Nombre",
    email_placeholder: "Correo electrónico",
    message_placeholder: "¿Cómo podemos ayudar?",
    submit: "Enviar",
    page_not_found: "Página no encontrada",
    page_not_found_description: "La página que busca no existe, pero nuestra misión continúa.",
    return_home: "Volver al inicio",
    planned: "Planeado",
    events: "Eventos",
    events_title: "Calendario de eventos de ERI: próximos, pasados y momentos de impacto futuro.",
    read_more: "Leer más",
    learn_more: "Más información",
    highlights: "Aspectos destacados",
    our_work: "Nuestro trabajo",
    supporting_communities: "Apoyando comunidades con acción práctica y cuidado",
    featured_programs: "Programas destacados",
    programs_that_deepen_outreach: "Programas que fortalecen la extensión y el apoyo a largo plazo",
    flagship_initiatives: "Iniciativas destacadas",
    coastal_resilience: "Resiliencia costera",
    local_solutions: "Soluciones locales que protegen a las personas y a los ecosistemas",
    learn_more_short: "Más información",
    journey_highlight: "Punto clave del recorrido",
    our_journey: "Nuestro recorrido",
    open_gallery: "Abrir galería",
    close: "Cerrar",
    collaboration_strengthens_community_care: "Colaboración que fortalece el cuidado comunitario",
    partners_intro: "ERI trabaja a través de una amplia red de socios, comunidades de fe y voluntarios de primera línea para hacer que la extensión sea más confiable, más receptiva y más sostenible.",
    ambassadors_strengthen_trust: "Los embajadores fortalecen la confianza",
    faith_based_collaboration: "Colaboración basada en la fe",
    partner_led_referrals: "Referencias dirigidas por socios",
    faith_based_and_community_partnerships: "Alianzas de fe y comunidad",
    why_partnerships_matter: "Por qué estas alianzas importan",
    partners_tag: "Socios",
  },
};

const supplementalTranslations: Record<Lang, Record<string, string>> = {
  en: {
    volunteer_form_title: "Volunteer sign-up",
    volunteer_form_description: "Tell us a little about yourself and how you would like to support ERI.",
    full_name_placeholder: "Full name",
    phone_placeholder: "Phone number",
    location_placeholder: "Town or location",
    full_name: "Full name",
    interests_label: "Volunteer interests",
    experience_label: "Relevant experience",
    motivation_label: "Motivation",
    preferred_date: "Preferred date",
    preferred_time: "Preferred time",
    availability_placeholder: "Availability (days and times)",
    interests_placeholder: "Volunteer interests",
    experience_placeholder: "Relevant experience (optional)",
    motivation_placeholder: "Why would you like to volunteer?",
    submit_application: "Submit application",
    sending: "Sending...",
    volunteer_success: "Thank you. Your volunteer application has been sent to ERI.",
    volunteer_error: "We could not send your application. Please try again or email eriinitiative@gmail.com.",
    value_dignity_first: "Dignity first",
    value_dignity_first_text: "We meet each person with empathy, respect, and a clear pathway to belonging.",
    value_community_care: "Community-led care",
    value_community_care_text: "Our work is shaped by families, local leaders, and trusted partners in Nairobi and beyond.",
    value_sustainable_change: "Sustainable change",
    value_sustainable_change_text: "We connect people to skills, documentation, health care, and safe reintegration support.",
    hero_restoring_dignity: "Restoring dignity for street-connected Kenyans",
    hero_connecting_support: "Connecting people to shelter, healthcare, and legal support",
    hero_building_pathways: "Building safer pathways to education and livelihoods",
    home_eri_system: "The ERI system",
    home_eri_system_text: "ERI supports street-connected individuals with holistic support, including shelter, medical care, legal identity, counseling, and reintegration planning.",
    home_how_help: "How we help",
    home_how_help_text: "Our programs identify urgent needs, coordinate recovery services, and empower people with the skills and stability needed to rebuild their lives.",
    home_street_outreach: "Street outreach",
    home_street_outreach_text: "Mobile teams connect directly with individuals on the street to deliver food, hygiene, and referrals to safe spaces.",
    home_case_management: "Case management",
    home_case_management_text: "Personalized support plans ensure people receive shelter, counseling, health care, and legal documentation.",
    home_skills_reintegration: "Skills & reintegration",
    home_skills_reintegration_text: "Training, education, and livelihood pathways help participants move from crisis to independence.",
    phone: "Phone",
    location: "Location",
    donation_success: "Thank you for supporting ERI. Your donation is being processed.",
    donation_cancelled: "Donation cancelled. You can try again any time.",
    donation_demo: "Demo mode is active. No real payment was processed.",
    custom_amount: "Custom amount",
    amount_placeholder: "Enter amount in KES",
    selected_donation: "Selected donation",
    processing: "Processing...",
  },
  sw: {
    volunteer_form_title: "Usajili wa kujitolea",
    volunteer_form_description: "Tuambie kidogo kukuhusu na jinsi ungependa kusaidia ERI.",
    full_name_placeholder: "Jina kamili",
    phone_placeholder: "Nambari ya simu",
    location_placeholder: "Mji au eneo",
    full_name: "Jina kamili",
    interests_label: "Maeneo ya kujitolea",
    experience_label: "Uzoefu unaohusiana",
    motivation_label: "Sababu ya kujitolea",
    preferred_date: "Tarehe inayopendelewa",
    preferred_time: "Muda unaopendelewa",
    availability_placeholder: "Upatikanaji (siku na muda)",
    interests_placeholder: "Maeneo ya kujitolea",
    experience_placeholder: "Uzoefu unaohusiana (si lazima)",
    motivation_placeholder: "Kwa nini ungependa kujitolea?",
    submit_application: "Tuma ombi",
    sending: "Inatumwa...",
    volunteer_success: "Asante. Ombi lako la kujitolea limetumwa kwa ERI.",
    volunteer_error: "Hatukuweza kutuma ombi lako. Jaribu tena au tuma barua pepe kwa eriinitiative@gmail.com.",
    value_dignity_first: "Heshima kwanza",
    value_dignity_first_text: "Tunampokea kila mtu kwa huruma, heshima, na njia wazi ya kujumuishwa.",
    value_community_care: "Huduma inayoongozwa na jamii",
    value_community_care_text: "Kazi yetu inaongozwa na familia, viongozi wa eneo, na washirika wanaoaminika Nairobi na kwingineko.",
    value_sustainable_change: "Mabadiliko endelevu",
    value_sustainable_change_text: "Tunawaunganisha watu na ujuzi, nyaraka, huduma za afya, na msaada salama wa kuunganishwa tena na jamii.",
    hero_restoring_dignity: "Kurejesha heshima kwa Wakenya walio kwenye mitaa",
    hero_connecting_support: "Kuunganisha watu na makazi, huduma za afya, na msaada wa kisheria",
    hero_building_pathways: "Kujenga njia salama za elimu na riziki",
    home_eri_system: "Mfumo wa ERI",
    home_eri_system_text: "ERI huwasaidia watu walio kwenye mitaa kwa makazi, huduma za afya, utambulisho wa kisheria, ushauri, na mipango ya kuunganishwa tena na jamii.",
    home_how_help: "Jinsi tunavyosaidia",
    home_how_help_text: "Programu zetu hutambua mahitaji ya haraka, huratibu huduma za urejeshaji, na kuwawezesha watu kujenga upya maisha yao.",
    home_street_outreach: "Huduma za mitaani",
    home_street_outreach_text: "Timu za kusafiri huwasiliana moja kwa moja na watu mitaani kutoa chakula, usafi, na rufaa kwa maeneo salama.",
    home_case_management: "Usimamizi wa kesi",
    home_case_management_text: "Mipango binafsi ya msaada huhakikisha watu wanapata makazi, ushauri, huduma za afya, na nyaraka za kisheria.",
    home_skills_reintegration: "Ujuzi na kuunganishwa tena",
    home_skills_reintegration_text: "Mafunzo, elimu, na njia za riziki huwasaidia washiriki kutoka kwenye tatizo hadi kujitegemea.",
    phone: "Simu",
    location: "Mahali",
    donation_success: "Asante kwa kuunga mkono ERI. Mchango wako unachakatwa.",
    donation_cancelled: "Mchango umeghairiwa. Unaweza kujaribu tena wakati wowote.",
    donation_demo: "Hali ya majaribio iko wazi. Hakuna malipo halisi yaliyofanywa.",
    custom_amount: "Kiasi maalum",
    amount_placeholder: "Weka kiasi kwa KES",
    selected_donation: "Mchango uliochaguliwa",
    processing: "Inachakatwa...",
  },
  fr: {
    volunteer_form_title: "Inscription comme bénévole",
    volunteer_form_description: "Parlez-nous de vous et de la manière dont vous souhaitez soutenir ERI.",
    full_name_placeholder: "Nom complet",
    phone_placeholder: "Numéro de téléphone",
    location_placeholder: "Ville ou lieu",
    full_name: "Nom complet",
    interests_label: "Domaines de bénévolat",
    experience_label: "Expérience pertinente",
    motivation_label: "Motivation",
    preferred_date: "Date souhaitée",
    preferred_time: "Heure souhaitée",
    availability_placeholder: "Disponibilités (jours et heures)",
    interests_placeholder: "Domaines de bénévolat",
    experience_placeholder: "Expérience pertinente (facultatif)",
    motivation_placeholder: "Pourquoi souhaitez-vous être bénévole ?",
    submit_application: "Envoyer la candidature",
    sending: "Envoi...",
    volunteer_success: "Merci. Votre candidature bénévole a été envoyée à ERI.",
    volunteer_error: "Nous n'avons pas pu envoyer votre candidature. Réessayez ou écrivez à eriinitiative@gmail.com.",
    phone: "Téléphone",
    location: "Lieu",
    donation_success: "Merci de soutenir ERI. Votre don est en cours de traitement.",
    donation_cancelled: "Don annulé. Vous pouvez réessayer à tout moment.",
    donation_demo: "Le mode démo est actif. Aucun paiement réel n'a été effectué.",
    custom_amount: "Montant personnalisé",
    amount_placeholder: "Saisissez le montant en KES",
    selected_donation: "Don sélectionné",
    processing: "Traitement...",
  },
  de: {
    volunteer_form_title: "Als Freiwilliger anmelden",
    volunteer_form_description: "Erzählen Sie uns etwas über sich und wie Sie ERI unterstützen möchten.",
    full_name_placeholder: "Vollständiger Name",
    phone_placeholder: "Telefonnummer",
    location_placeholder: "Ort oder Stadt",
    full_name: "Vollständiger Name",
    interests_label: "Interessen für Freiwilligenarbeit",
    experience_label: "Relevante Erfahrung",
    motivation_label: "Motivation",
    preferred_date: "Bevorzugtes Datum",
    preferred_time: "Bevorzugte Uhrzeit",
    availability_placeholder: "Verfügbarkeit (Tage und Zeiten)",
    interests_placeholder: "Interessen für Freiwilligenarbeit",
    experience_placeholder: "Relevante Erfahrung (optional)",
    motivation_placeholder: "Warum möchten Sie sich engagieren?",
    submit_application: "Bewerbung senden",
    sending: "Wird gesendet...",
    volunteer_success: "Danke. Ihre Bewerbung wurde an ERI gesendet.",
    volunteer_error: "Ihre Bewerbung konnte nicht gesendet werden. Versuchen Sie es erneut oder schreiben Sie an eriinitiative@gmail.com.",
    phone: "Telefon",
    location: "Ort",
    donation_success: "Danke für Ihre Unterstützung von ERI. Ihre Spende wird bearbeitet.",
    donation_cancelled: "Spende storniert. Sie können es jederzeit erneut versuchen.",
    donation_demo: "Der Demomodus ist aktiv. Es wurde keine echte Zahlung verarbeitet.",
    custom_amount: "Benutzerdefinierter Betrag",
    amount_placeholder: "Betrag in KES eingeben",
    selected_donation: "Ausgewählte Spende",
    processing: "Wird verarbeitet...",
  },
  es: {
    volunteer_form_title: "Registro de voluntariado",
    volunteer_form_description: "Cuéntanos un poco sobre ti y cómo te gustaría apoyar a ERI.",
    full_name_placeholder: "Nombre completo",
    phone_placeholder: "Número de teléfono",
    location_placeholder: "Ciudad o ubicación",
    full_name: "Nombre completo",
    interests_label: "Intereses de voluntariado",
    experience_label: "Experiencia relevante",
    motivation_label: "Motivación",
    preferred_date: "Fecha preferida",
    preferred_time: "Hora preferida",
    availability_placeholder: "Disponibilidad (días y horarios)",
    interests_placeholder: "Intereses de voluntariado",
    experience_placeholder: "Experiencia relevante (opcional)",
    motivation_placeholder: "¿Por qué te gustaría ser voluntario?",
    submit_application: "Enviar solicitud",
    sending: "Enviando...",
    volunteer_success: "Gracias. Tu solicitud de voluntariado se envió a ERI.",
    volunteer_error: "No pudimos enviar tu solicitud. Inténtalo de nuevo o escribe a eriinitiative@gmail.com.",
    phone: "Teléfono",
    location: "Ubicación",
    donation_success: "Gracias por apoyar a ERI. Su donación está siendo procesada.",
    donation_cancelled: "Donación cancelada. Puede intentarlo de nuevo en cualquier momento.",
    donation_demo: "El modo de demostración está activo. No se procesó ningún pago real.",
    custom_amount: "Cantidad personalizada",
    amount_placeholder: "Ingrese la cantidad en KES",
    selected_donation: "Donación seleccionada",
    processing: "Procesando...",
  },
};

const LanguageContext = createContext<LangContext | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    return (localStorage.getItem("eri_lang") as Lang) || "en";
  });

  useEffect(() => {
    localStorage.setItem("eri_lang", lang);
  }, [lang]);

  function setLang(l: Lang) {
    setLangState(l);
  }

  function t(key: string) {
    return translations[lang][key] ?? supplementalTranslations[lang][key] ?? translations.en[key] ?? supplementalTranslations.en[key] ?? key;
  }

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export default LanguageProvider;
