"use client";

import Link from 'next/link';

export default function ProblemStatementBlogPost() {
  return (
    <main className="mx-auto max-w-5xl px-6 py-16 lg:px-8">
      <div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm">
        <p className="text-sm font-semibold uppercase tracking-[0.25em] text-olive">Blog</p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight text-navy">Understanding Street-Connectedness: Why ERI Exists</h1>
        <p className="mt-4 text-sm text-slate-500">Published 22 August 2026 · 10 minute read</p>
        <p className="mt-6 text-lg leading-8 text-slate-700">Street-connectedness is not only a housing challenge—it is also a reflection of poverty, family breakdown, missed education, drug abuse, and weak social support systems. ERI was founded to respond to that reality with dignity, rehabilitation, and long-term reintegration.</p>
        <div className="mt-8 rounded-3xl border border-slate-200 bg-cream p-6">
          <h2 className="text-xl font-semibold text-navy">ERI’s response</h2>
          <p className="mt-3 text-slate-600">Our work combines direct support, community engagement, and practical pathways that help people move from crisis toward safety, belonging, and lasting change.</p>
        </div>
        <div className="mt-8 space-y-8 text-slate-600">
          <section><h2 className="text-2xl font-semibold text-navy">A person is more than a label</h2><p className="mt-3 leading-8">The phrase street-connectedness describes a relationship with streets and public spaces, but it does not describe a person’s whole identity. People may spend time on the street for different reasons and for different lengths of time. Some remain connected to family; others have lost contact. Some move between temporary homes, work, school, and public spaces.</p><p className="mt-3 leading-8">Using careful language matters because labels can shape how people are treated. ERI’s starting point is to ask what has happened, what is unsafe now, and what support could make the next step possible. Listening is not a delay before action; it is part of accurate assessment.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">The pressures behind street-connectedness</h2><p className="mt-3 leading-8">Poverty can turn a short-term setback into a prolonged crisis when a household has no savings, secure housing, or reliable income. Family breakdown, violence, bereavement, disability, untreated illness, and substance use can add further pressure. Missed education and missing identity documents can then reduce access to jobs, health care, and protection.</p><p className="mt-3 leading-8">These pressures often overlap. It is therefore unrealistic to expect one service or one conversation to solve them all. Effective support needs coordination, patience, and a willingness to return to the plan when circumstances change.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">Why immediate support still matters</h2><p className="mt-3 leading-8">Long-term rehabilitation begins with immediate safety. Food, hygiene supplies, medical attention, a safe conversation, or help replacing a document can reduce the pressure a person is carrying today. These actions do not solve every structural cause, but they create enough stability for planning and follow-up to become possible.</p><p className="mt-3 leading-8">Practical help should be offered without conditions that punish people for being in crisis. At the same time, it should connect to a wider plan whenever the person wants that support. Relief and rehabilitation are not competing ideas; immediate care can be the first step toward sustained change.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">Rehabilitation is a pathway, not a single service</h2><p className="mt-3 leading-8">A rehabilitation pathway may include outreach, assessment, health care, counseling, family work, education, skills development, legal identity, protection, and livelihood support. The order will differ from person to person. Someone may need safety and medical care first, while another person may be ready to return to learning or work.</p><p className="mt-3 leading-8">The important principle is continuity. People should not have to restart their story at every stage. Case coordination and trusted follow-up help turn separate services into a pathway that reflects the person’s goals and changing needs.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">The role of families and communities</h2><p className="mt-3 leading-8">Reintegration cannot be imposed from outside. Families and communities need support to understand what has happened, rebuild communication, and create conditions that are safe for everyone. Community leaders can help identify trusted contacts and reduce stigma, while service providers can address needs that families cannot manage alone.</p><p className="mt-3 leading-8">When returning home is not immediately safe or possible, the plan must be honest about alternatives. Dignity means avoiding pressure to reunite without preparation and keeping the person involved in decisions about their future.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">What progress can look like</h2><p className="mt-3 leading-8">Progress is not always dramatic. It can mean attending an appointment, replacing a lost document, sleeping safely for a week, reconnecting with a trusted relative, returning to class, learning a skill, or reducing exposure to violence. Small steps matter because stability is built through repeated experiences of safety and agency.</p><p className="mt-3 leading-8">ERI measures progress with humility. Numbers can show reach and activity, but they do not replace listening to people about whether support is useful, respectful, and making life more stable.</p></section>
          <section><h2 className="text-2xl font-semibold text-navy">Why ERI exists</h2><p className="mt-3 leading-8">ERI exists because people deserve more than temporary visibility. The organization brings outreach, practical support, community partnerships, and long-term reintegration work into one connected response. That work is demanding and cannot be completed by one organization alone.</p><p className="mt-3 leading-8">The clearest measure of success is a future in which people can access safety, identity, education, health care, belonging, and livelihoods without having to remain in crisis to be noticed. Building that future requires patience, accountability, and the conviction that every person can participate in shaping their next chapter.</p></section>
        </div>
        <div className="mt-8">
          <Link href="/news" className="inline-flex rounded-full bg-olive px-5 py-3 font-semibold text-white">Back to news</Link>
        </div>
      </div>
    </main>
  );
}
